@isTest
public with sharing class AccConAndOppOperationsTest {

// Code Coverage 60 %

    @isTest
    public static void method1Test() {
        AccConAndOppOperations.method1();
    }

    @isTest
    public static void method2Test() {

    AccConAndOppOperations.method2('');
    }

    @isTest
    public static void method3Test() {

    AccConAndOppOperations.method3('');
    }

    @isTest
    public static void method4Test() {
        AccConAndOppOperations.method4('' , '');
        }
    

    @isTest
    public static void method5Test() {
        AccConAndOppOperations.method5();
        }

        @isTest
    public static void method6Test() {
        AccConAndOppOperations.method6('');
        }

        @isTest
        public static void method7Test() {
            AccConAndOppOperations.method7();
            }

        @isTest
        public static void method8Test() {
        AccConAndOppOperations.method8();
        }

        @isTest
        public static void method1_P2_Test() {
        AccConAndOppOperations.method1_P2('', 0 , '');
        }

        @isTest
        public static void method2_P2_Test() {
        AccConAndOppOperations.method2_P2('');
        }

        @isTest
        public static void method3_P2_Test() {
        AccConAndOppOperations.method3_P2();
        }

        @isTest
        public static void specOpp_Test() {
        AccConAndOppOperations.specOpp('' , 0);
        }

        @isTest
        public static void method5_P2_Test() {
        AccConAndOppOperations.method5_P2();
        }

        @isTest
        public static void nonAssAcc_Test() {
        AccConAndOppOperations.nonAssAcc();
        }

        @isTest
        public static void method7_P2_Test() {
        AccConAndOppOperations.method7_P2();
        }

        





        















}
