public class Address {
    public void homeAddress() {
        string YourName = 'Tuba Bilir';
        integer TotalFamMember = 4;
        string HouseName = 'My Home';
        string HouseNumber = '403';
        string StreetName = 'Oaksway';
        string CityName = 'Miami';
        string StateName = 'Florida';
        string ISOcode = 'FL';
        string CountryName = 'United States';
        string CountryIso = 'USA';
        string zipCode = '33069';
        boolean currentHome = true;


        system.debug('My name is = ' + YourName );
        system.debug('Total number of family members = ' + TotalFamMember);
        system.debug('My house name is = ' + HouseName );
        system.debug('My house number is = ' + HouseNumber );
        system.debug('My street name is = ' + YourName );
        system.debug('My city name is = ' + CityName );
        system.debug('My state name is = ' + StateName );
        system.debug('My states iso code is = ' + ISOcode );
        system.debug('My country name is = ' + CountryName );
        system.debug('My country\'s iso code is = ' + CountryIso );
        system.debug('My zip code is = ' + zipCode );
        system.debug('Is this your current home? = ' + currentHome );
    }



}

