public class Carsamba {
    public void welcome() {
        system.debug('Welcome');
    }

    public void welcome(string wl){
        system.debug('Welcome ' + wl);
    }

    public string stringMetot1(string str){
        string cml = str + ' Okula gitti';
        return cml;
    }

    public integer sum(integer a, integer b){
        return a + b;
    }

    public integer uzunluk(string st){
        integer uz = st.length();
        return uz;
    }

    






}
