public  class MyIntroduction {
    public void printMyIntroduction() {

 string fullName = 'Tuba Bilir' ;      
 string myLocation = 'Miami';
 string myHobbies = 'Not Apex, Traveling, Netflix, Photography';
 boolean backgroundIt = false;
 string profession = 'Screenwriter';

system.debug('Here is my introduction = ' + fullName);
system.debug('I m living in ' + myLocation );
system.debug('My hobbies is ' + myHobbies );
system.debug('IT Background? ' + backgroundIt );
system.debug('My profession is ' + profession  );
    }
}
