public class Tesst {

    public integer topla(integer a, integer b){
        integer sum1 = a + b ;
        return sum1;
    }

    // renk kirmzi marka mercedes model cla 250 vites otomatik km 0

    public string carColor; 
    public string carMarka; 
    public string carModel; 
    public string carVites; 
    public integer carKm;

    public string myCar(){
        string descr = ' Arabamin rengi '+ carColor + ' arabamin markasi ' + carMarka + ' arabamin modeli ' + carModel + ' vites ' + carVites + ' km ' + carKm ;
    return descr;

    }

}