Candidates.CompanyName = 'SoftInnovas';

Candidates.printCandidateInfo();
Candidates.CompanyName += ' INC';
Candidates.printCandidateInfo();

Candidates c1 = new Candidates();
c1.Name = 'jerry';
c1.Gender = 'male';
c1.printCandidate();

Candidates c2 = new Candidates();
c2.Name = 'Elaine';
c2.Gender = 'female';
c2.printCandidate();

Candidates.CompanyName = 'Vandley';
Candidates c3 = new Candidates();
c3.Name = 'George';
c3.Gender = 'male';
c3.printCandidate();






